import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://demowebshop.tricentis.com/');
  await page.getByRole('link', { name: 'Register' }).click();
  await page.getByRole('radio', { name: 'Male', exact: true }).check();
  await page.getByText('Gender:').click();
  await page.getByText('Male', { exact: true }).click();
  await page.getByRole('radio', { name: 'Male', exact: true }).check();
  await page.getByText('Female').click();
  await page.getByRole('radio', { name: 'Female' }).check();
  await page.getByRole('radio', { name: 'Male', exact: true }).check();
  await page.getByRole('textbox', { name: 'First name:' }).click();
  await page.getByRole('textbox', { name: 'First name:' }).fill('michael');
  await page.getByRole('textbox', { name: 'Last name:' }).click();
  await page.getByText('Last name:').click();
  await page.getByRole('textbox', { name: 'Last name:' }).click();
  await page.getByRole('textbox', { name: 'Last name:' }).click();
  await page.getByRole('textbox', { name: 'Last name:' }).fill('mike');
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('mikaelochem90@gmail.com');
  await page.locator('.page-body > div:nth-child(3) > .title').click();
  await page.getByRole('textbox', { name: 'Password:', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password:', exact: true }).click();
  await page.getByRole('textbox', { name: 'Password:', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password:', exact: true }).fill('A');
  await page.getByRole('textbox', { name: 'Password:', exact: true }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password:', exact: true }).fill('Ania1990@');
  await page.getByRole('textbox', { name: 'Confirm password:' }).click();
  await page.getByText('Confirm password:').click();
  await page.getByRole('textbox', { name: 'Confirm password:' }).click();
  await page.getByRole('textbox', { name: 'Confirm password:' }).click();
  await page.getByRole('textbox', { name: 'Confirm password:' }).fill('');
  await page.getByRole('textbox', { name: 'Confirm password:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirm password:' }).fill('A');
  await page.getByRole('textbox', { name: 'Confirm password:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Confirm password:' }).fill('Ania1990@');
  await page.locator('div').filter({ hasText: 'Register Your Personal' }).nth(3).click();
  await page.getByRole('button', { name: 'Register' }).click();
  await page.locator('div').filter({ hasText: 'Register Your registration' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'Register Your registration' }).nth(3).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('link', { name: 'Log out' }).click();
  await page.getByRole('link', { name: 'Log in' }).click();
  await page.locator('div').nth(3).click();
  await page.locator('div').filter({ hasText: 'Welcome, Please Sign In! New' }).nth(3).click();
  await page.locator('div').filter({ hasText: 'Welcome, Please Sign In! New' }).nth(3).click();
  await page.getByText('Returning Customer Email:').click();
  await page.locator('.inputs').first().click();
  await page.getByRole('textbox', { name: 'Email:' }).click();
  await page.getByRole('textbox', { name: 'Email:' }).fill('mikaelochem90@gmail.com');
  await page.getByRole('textbox', { name: 'Password:' }).click();
  await page.getByRole('textbox', { name: 'Password:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password:' }).fill('A');
  await page.getByRole('textbox', { name: 'Password:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Password:' }).fill('Ania1990@');
  await page.getByRole('checkbox', { name: 'Remember me?' }).check();
  await page.getByRole('checkbox', { name: 'Remember me?' }).dblclick();
  await page.getByRole('checkbox', { name: 'Remember me?' }).check();
  await page.getByText('Returning Customer Email:').click();
  await page.getByRole('button', { name: 'Log in' }).click();
  await page.locator('div').nth(4).click();
  await page.locator('div').nth(4).click();
  await page.locator('div').nth(4).click();
  await page.getByRole('button', { name: 'Add to cart' }).first().click();
  await page.getByText('$25 Virtual Gift Card $25').click();
  await page.getByRole('textbox', { name: 'Recipient\'s Name:' }).click();
  await page.getByRole('textbox', { name: 'Recipient\'s Name:' }).fill('mike');
  await page.getByRole('textbox', { name: 'Recipient\'s Email:' }).click();
  await page.getByRole('textbox', { name: 'Recipient\'s Email:' }).fill('mike@yopmail.com');
  await page.getByRole('textbox', { name: 'Message:' }).click();
  await page.getByRole('textbox', { name: 'Message:' }).fill('thanks');
  await page.locator('#add-to-cart-button-2').click();
  await page.getByText('The product has been added to your shopping cart mikaelochem90@gmail.com Log').click();
  await page.goto('https://demowebshop.tricentis.com/');
  await page.locator('div').nth(4).click();
  await page.locator('div').nth(4).click();
  await page.getByRole('button', { name: 'Add to cart' }).nth(2).click();
  await page.locator('#add-to-cart-button-72').click();
  await page.locator('#add-to-cart-button-72').click();
  await page.goto('https://demowebshop.tricentis.com/');
  await page.getByRole('button', { name: 'Add to cart' }).nth(5).click();
  await page.getByText('Qty: Add to cart').click();
  await page.locator('#add-to-cart-button-75').click();
  await page.getByRole('button', { name: 'Add to cart' }).nth(2).click();
  await page.locator('#add-to-cart-button-28').click();
  await page.locator('.product-essential').click();
  await page.locator('li:nth-child(2) > label > .color-container > .color').click();
  await page.locator('#product_attribute_28_1_11_30').check();
  await page.locator('#product_attribute_28_1_11_30').click();
  await page.locator('#product_attribute_28_1_11_30').check();
  await page.locator('#add-to-cart-button-28').click();
  await page.getByRole('link', { name: 'Electronics' }).first().click();
  await page.getByRole('listitem').filter({ hasText: 'Apparel & Shoes' }).first().click();
  await page.getByRole('link', { name: 'Jewelry' }).first().click();
  await page.getByText('130.00 Add to cart').click();
  await page.getByRole('button', { name: 'Add to cart' }).nth(1).click();
  await page.getByRole('button', { name: 'Add to cart' }).first().click();
  await page.locator('#add-to-cart-button-71').click();
  await page.locator('#add-to-cart-button-71').click();
  await page.getByRole('link', { name: 'Shopping cart (6)' }).click();
  await page.getByRole('link', { name: 'Shopping cart (6)' }).click();
  await page.locator('div').filter({ hasText: 'Shopping cart Remove Product(' }).nth(3).click();
  await page.getByRole('row', { name: 'Picture of Blue and green Sneaker Blue and green Sneaker Size: 8 Color: White' }).getByRole('checkbox').check();
  await page.getByRole('columnheader', { name: 'Remove' }).click();
  await page.getByRole('columnheader', { name: 'Remove' }).click();
  await page.getByRole('columnheader', { name: 'Remove' }).click();
  await page.locator('.cart-collaterals').click();
  await page.getByRole('button', { name: 'Update shopping cart' }).click();
  await page.getByLabel('Country:').selectOption('186');
  await page.getByText('Estimate shipping Enter your').click();
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).click();
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).fill('23456');
  await page.getByText('Sub-Total: 1796.00 Shipping: 0.00 Tax: 0.00 Total: 1796.00 Please accept the').click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('dialog', { name: 'Terms of service' }).dblclick();
  await page.locator('.cart-collaterals').click();
  await page.getByRole('dialog', { name: 'Terms of service' }).click();
  await page.locator('#terms-of-service-warning-box').click();
  await page.getByText('Sub-Total: 1796.00 Shipping: 0.00 Tax: 0.00 Total: 1796.00 I agree with the').click();
  await page.getByRole('button', { name: 'close' }).click();
  await page.getByRole('button', { name: 'Estimate shipping' }).click();
  await page.getByText('Pick up your items at the').click();
  await page.locator('#termsofservice').check();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByRole('textbox', { name: 'Company:' }).click();
  await page.getByRole('textbox', { name: 'Company:' }).fill('');
  await page.getByRole('textbox', { name: 'Company:' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Company:' }).fill('ABCD');
  await page.locator('div:nth-child(9)').click();
  await page.getByRole('textbox', { name: 'City:' }).click();
  await page.getByRole('textbox', { name: 'City:' }).fill('LAGOS');
  await page.getByRole('textbox', { name: 'Address 2:' }).click();
  await page.getByRole('textbox', { name: 'Address 1:' }).click();
  await page.getByRole('textbox', { name: 'Address 1:' }).fill('TEST STREET');
  await page.getByRole('textbox', { name: 'Address 2:' }).click();
  await page.getByRole('textbox', { name: 'Address 2:' }).fill('SEC');
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).click();
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).fill('12345608122222222');
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).click();
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).press('ControlOrMeta+C');
  await page.getByRole('textbox', { name: 'Zip / postal code:' }).fill('123456');
  await page.getByRole('textbox', { name: 'Phone number:' }).click();
  await page.getByRole('textbox', { name: 'Phone number:' }).press('ControlOrMeta+V');
  await page.getByRole('textbox', { name: 'Phone number:' }).fill('08122222222');
  await page.locator('.enter-address').click();
  await page.getByRole('textbox', { name: 'Fax number:' }).click();
  await page.getByRole('textbox', { name: 'Fax number:' }).fill('01234567');
  await page.locator('div').filter({ hasText: 'Checkout 1 Billing address' }).nth(3).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByLabel('Country:').selectOption('186');
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('body').click();
  await page.getByRole('checkbox', { name: 'In-Store Pickup' }).check();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.goto('https://demowebshop.tricentis.com/checkout/completed/');
  await page.getByText('Your order has been successfully processed! Order number: 2388776 Click here').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.locator('div').filter({ hasText: 'Thank you Your order has been' }).nth(3).click();
  await page.getByRole('link', { name: 'Log out' }).click();
  await page.getByRole('link', { name: 'Log out' }).click();
});